# AG32VF303 4-Channel High-Speed Logic Analyzer Project
# Board: AGM QFN32 Target Board (AG32VF303)
# Protocols: SUMP / Openbench Logic Sniffer (OLS) compatible
# Communication: USB 2.0 Full-Speed CDC-ACM Virtual Serial & UART0

[platformio]
default_envs = logic_analyzer
src_dir = .
include_dir = ./src

[setup]
board = agrv2k_303
framework = agrv_sdk, agrv_tinyusb
program = ag32_logic_analyzer
build_src_filter = "-<*> +<./src/*.c>"

[setup_logic]
logic_ve = logic_board.ve
logic_compress = true
logic_device = AGRV2KQ32
ip_name = analog_ip
logic_dir = logic

[setup_upload]
protocol = cmsis-dap-openocd
debug_tool = ${this.protocol}
upload_protocol = ${this.protocol}

[setup_monitor]
logger_if = UART0
monitor_port = COM26
monitor_speed = 115200

[env]
platform = AgRV
extends =
  setup
  setup_logic
  setup_upload
  setup_monitor

[env:logic_analyzer]
extends = env
build_type = release
build_flags = -O3
