[platformio]
default_envs = foc
src_dir = .
include_dir = ./src

[setup]
board = agrv2k_303
framework = agrv_sdk
program = can_uart_test
build_src_filter = "-<*> +<./src/*.c>"

[setup_logic]
logic_ve = test.ve
logic_device = AGRV2KQ32
logic_compress = true

[setup_upload]
protocol = cmsis-dap-openocd
debug_tool = ${this.protocol}
upload_protocol = ${this.protocol}

[env]
platform = AgRV
extends =
  setup
  setup_logic
  setup_upload

[env:foc]
extends = env
build_type = release
